version: '3.9'

services:
  database:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=panel
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=g7y5foaq
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


  panel:
    image: ghcr.io/pterodactyl/panel:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
    environment:
      - APP_URL=http://127.0.0.1
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=panel
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=g7y5fiaq
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
    volumes:
      - ./panel_data:/app/var/

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      - TZ=UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./wings_data:/var/lib/pterodactyl
      - ./wings_data/config.yml:/etc/pterodactyl/config.yml
    restart: always

  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft_data:/data
    environment:
      - EULA=TRUE
    restart: unless-stopped


